// 导出面与产物门禁: index.ts 是唯一导出面, 导出清单冻结(增删导出必须改这里的快照);
// package.json exports 指向的文件必须真实存在
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import * as ui from '../../src/index';

// 冻结的公共导出面(与 src/index.ts 一一对应)
const EXPECTED_EXPORTS = [
  // 基础
  'cn',
  // primitives
  'AlertDialog',
  'AlertDialogAction',
  'AlertDialogCancel',
  'AlertDialogContent',
  'AlertDialogDescription',
  'AlertDialogFooter',
  'AlertDialogHeader',
  'AlertDialogMedia',
  'AlertDialogOverlay',
  'AlertDialogPortal',
  'AlertDialogTitle',
  'AlertDialogTrigger',
  'Avatar',
  'AvatarImage',
  'AvatarFallback',
  'AvatarGroup',
  'AvatarGroupCount',
  'AvatarBadge',
  'Badge',
  'badgeVariants',
  'Button',
  'buttonVariants',
  'Card',
  'CardHeader',
  'CardFooter',
  'CardTitle',
  'CardAction',
  'CardDescription',
  'CardContent',
  'Collapsible',
  'CollapsibleTrigger',
  'CollapsibleContent',
  'Command',
  'CommandDialog',
  'CommandInput',
  'CommandList',
  'CommandEmpty',
  'CommandGroup',
  'CommandItem',
  'CommandShortcut',
  'CommandSeparator',
  'Dialog',
  'DialogClose',
  'DialogContent',
  'DialogDescription',
  'DialogFooter',
  'DialogHeader',
  'DialogOverlay',
  'DialogPortal',
  'DialogTitle',
  'DialogTrigger',
  'Drawer',
  'DrawerPortal',
  'DrawerOverlay',
  'DrawerSwipeHandle',
  'DrawerTrigger',
  'DrawerClose',
  'DrawerContent',
  'DrawerHeader',
  'DrawerFooter',
  'DrawerTitle',
  'DrawerDescription',
  'DropdownMenu',
  'DropdownMenuPortal',
  'DropdownMenuTrigger',
  'DropdownMenuContent',
  'DropdownMenuGroup',
  'DropdownMenuLabel',
  'DropdownMenuItem',
  'DropdownMenuCheckboxItem',
  'DropdownMenuRadioGroup',
  'DropdownMenuRadioItem',
  'DropdownMenuSeparator',
  'DropdownMenuShortcut',
  'DropdownMenuSub',
  'DropdownMenuSubTrigger',
  'DropdownMenuSubContent',
  'Kbd',
  'KbdGroup',
  'Popover',
  'PopoverContent',
  'PopoverDescription',
  'PopoverHeader',
  'PopoverTitle',
  'PopoverTrigger',
  'ScrollArea',
  'ScrollBar',
  'Separator',
  'Sheet',
  'SheetTrigger',
  'SheetClose',
  'SheetContent',
  'SheetHeader',
  'SheetFooter',
  'SheetTitle',
  'SheetDescription',
  'Skeleton',
  'Spinner',
  'ThemeProvider',
  'useTheme',
  'useThemeOptional',
  'Tooltip',
  'TooltipTrigger',
  'TooltipContent',
  'TooltipProvider',
  // forms
  'Checkbox',
  'Combobox',
  'ComboboxInput',
  'ComboboxContent',
  'ComboboxList',
  'ComboboxItem',
  'ComboboxGroup',
  'ComboboxLabel',
  'ComboboxCollection',
  'ComboboxEmpty',
  'ComboboxSeparator',
  'ComboboxChips',
  'ComboboxChip',
  'ComboboxChipsInput',
  'ComboboxTrigger',
  'ComboboxValue',
  'useComboboxAnchor',
  'Field',
  'FieldLabel',
  'FieldDescription',
  'FieldError',
  'FieldGroup',
  'FieldLegend',
  'FieldSeparator',
  'FieldSet',
  'FieldContent',
  'FieldTitle',
  'Input',
  'InputGroup',
  'InputGroupAddon',
  'InputGroupButton',
  'InputGroupText',
  'InputGroupInput',
  'InputGroupTextarea',
  'Label',
  'PasswordInput',
  'RadioGroup',
  'RadioGroupItem',
  'Select',
  'SelectContent',
  'SelectGroup',
  'SelectItem',
  'SelectLabel',
  'SelectScrollDownButton',
  'SelectScrollUpButton',
  'SelectSeparator',
  'SelectTrigger',
  'SelectValue',
  'Switch',
  'Textarea',
  'Toggle',
  'toggleVariants',
  'ToggleGroup',
  'ToggleGroupItem',
  // data
  'DataTable',
  'Empty',
  'EmptyHeader',
  'EmptyTitle',
  'EmptyDescription',
  'EmptyContent',
  'EmptyMedia',
  'KpiCard',
  'MoneyDisplay',
  'SecretReveal',
  'StatusPill',
  'Table',
  'TableHeader',
  'TableBody',
  'TableFooter',
  'TableHead',
  'TableRow',
  'TableCell',
  'TableCaption',
  // navigation
  'Breadcrumb',
  'BreadcrumbList',
  'BreadcrumbItem',
  'BreadcrumbLink',
  'BreadcrumbPage',
  'BreadcrumbSeparator',
  'BreadcrumbEllipsis',
  'Pagination',
  'PaginationContent',
  'PaginationEllipsis',
  'PaginationItem',
  'PaginationLink',
  'PaginationNext',
  'PaginationPrevious',
  'Sidebar',
  'SidebarContent',
  'SidebarFooter',
  'SidebarGroup',
  'SidebarGroupAction',
  'SidebarGroupContent',
  'SidebarGroupLabel',
  'SidebarHeader',
  'SidebarInput',
  'SidebarInset',
  'SidebarMenu',
  'SidebarMenuAction',
  'SidebarMenuBadge',
  'SidebarMenuButton',
  'SidebarMenuItem',
  'SidebarMenuSkeleton',
  'SidebarMenuSub',
  'SidebarMenuSubButton',
  'SidebarMenuSubItem',
  'SidebarProvider',
  'SidebarRail',
  'SidebarSeparator',
  'SidebarTrigger',
  'useSidebar',
  'Tabs',
  'TabsList',
  'TabsTrigger',
  'TabsContent',
  'tabsListVariants',
  'ThemeSwitcher',
  // feedback
  'Alert',
  'AlertTitle',
  'AlertDescription',
  'AlertAction',
  'ConfirmDialog',
  'CopyButton',
  'FormDialog',
  'Progress',
  'ProgressTrack',
  'ProgressIndicator',
  'ProgressLabel',
  'ProgressValue',
  'Toaster',
  'toast',
  // hooks
  'useCopy',
  'useIsMobile',
  'useMediaQuery',
  // formatting 工厂
  'createMoneyFormatter',
  'createNumberFormatter',
  'createDateFormatter',
] as const;

describe('index.ts 导出面', () => {
  it('导出清单与冻结快照一致(增删导出必须更新快照)', () => {
    expect(Object.keys(ui).toSorted()).toEqual([...EXPECTED_EXPORTS].toSorted());
  });

  it('每个导出都有真实值(无循环引用/未定义导出)', () => {
    for (const name of EXPECTED_EXPORTS) {
      expect(ui[name as keyof typeof ui]).toBeDefined();
    }
  });
});

describe('package.json exports 产物存在性', () => {
  const PKG_ROOT = join(import.meta.dirname, '../..');
  const pkg = JSON.parse(readFileSync(join(PKG_ROOT, 'package.json'), 'utf8'));

  it('样式入口指向真实文件', () => {
    const cssEntry = pkg.exports['./styles.css'];
    expect(typeof cssEntry).toBe('string');
    expect(existsSync(join(PKG_ROOT, cssEntry))).toBe(true);
  });

  it('根入口 development/types 指向真实源文件', () => {
    const root = pkg.exports['.'];
    expect(existsSync(join(PKG_ROOT, root.types))).toBe(true);
    expect(existsSync(join(PKG_ROOT, root.development))).toBe(true);
  });

  it('目录子路径(components/hooks/formatting)对应的 src 目录存在', () => {
    for (const sub of ['components', 'hooks', 'formatting']) {
      expect(existsSync(join(PKG_ROOT, 'src', sub))).toBe(true);
    }
  });
});
